package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// High Density / M3 Expressive Palette (from High Density design)
val HighDensityBackground = Color(0xFFFEF7FF)
val HighDensitySurface = Color(0xFFFEF7FF)
val HighDensitySurfaceContainer = Color(0xFFF3F3F7)
val HighDensitySurfaceContainerHigh = Color(0xFFEDE8F2)
val HighDensitySurfaceContainerHighest = Color(0xFFEADDFF)
val HighDensitySurfaceVariant = Color(0xFFCAC4D0)
val HighDensityOnSurface = Color(0xFF1D1B20)
val HighDensityOnSurfaceVariant = Color(0xFF49454F)

val HighDensityPrimary = Color(0xFF6750A4)
val HighDensityOnPrimary = Color(0xFFFFFFFF)
val HighDensityPrimaryContainer = Color(0xFFEADDFF)
val HighDensityOnPrimaryContainer = Color(0xFF21005D)

val HighDensitySecondary = Color(0xFFD0BCFF)
val HighDensityOnSecondary = Color(0xFF381E72)
val HighDensitySecondaryContainer = Color(0xFFE8DEF8)
val HighDensityOnSecondaryContainer = Color(0xFF1D192B)

val HighDensityTertiary = Color(0xFFFFD8E4) // Rose Accent for FAB
val HighDensityOnTertiary = Color(0xFF31111D)
val HighDensityTertiaryContainer = Color(0xFFFFD8E4)
val HighDensityOnTertiaryContainer = Color(0xFF31111D)

val HighDensityStatusGreen = Color(0xFF4CAF50)
val HighDensityBorder = Color(0xFFCAC4D0)

// 1. Dynamic / Default Monet Expressive Palette
val ExpressivePrimary = Color(0xFF6750A4)
val ExpressiveOnPrimary = Color(0xFFFFFFFF)
val ExpressivePrimaryContainer = Color(0xFFEADDFF)
val ExpressiveOnPrimaryContainer = Color(0xFF21005D)
val ExpressiveSecondary = Color(0xFFD0BCFF)
val ExpressiveTertiary = Color(0xFFFFD8E4)
val ExpressiveBackground = Color(0xFFFEF7FF)
val ExpressiveSurface = Color(0xFFFEF7FF)
val ExpressiveSurfaceVariant = Color(0xFFCAC4D0)
val ExpressiveAccent = Color(0xFFFF5449)

// 2. Electric Indigo (Vivid Royal Indigo & Cyan)
val IndigoPrimary = Color(0xFF4F46E5)
val IndigoPrimaryContainer = Color(0xFFE0E7FF)
val IndigoSecondary = Color(0xFF06B6D4)
val IndigoTertiary = Color(0xFF8B5CF6)
val IndigoBackground = Color(0xFFF8FAFC)
val IndigoSurface = Color(0xFFFFFFFF)

// 3. Sunset Coral (Warm Tangerine, Coral, Rose)
val CoralPrimary = Color(0xFFF95738)
val CoralPrimaryContainer = Color(0xFFFFE5E0)
val CoralSecondary = Color(0xFFEE964B)
val CoralTertiary = Color(0xFFF4D35E)
val CoralBackground = Color(0xFFFFFBF9)
val CoralSurface = Color(0xFFFFFFFF)

// 4. Neon Emerald (Mint, Jade, Cyber Lime)
val EmeraldPrimary = Color(0xFF059669)
val EmeraldPrimaryContainer = Color(0xFFD1FAE5)
val EmeraldSecondary = Color(0xFF10B981)
val EmeraldTertiary = Color(0xFF84CC16)
val EmeraldBackground = Color(0xFFF0FDF4)
val EmeraldSurface = Color(0xFFFFFFFF)

// 5. Electric Violet (Ultra Violet, Magenta, Neon Blue)
val VioletPrimary = Color(0xFF7C3AED)
val VioletPrimaryContainer = Color(0xFFEDE9FE)
val VioletSecondary = Color(0xFFEC4899)
val VioletTertiary = Color(0xFF3B82F6)
val VioletBackground = Color(0xFFFAF5FF)
val VioletSurface = Color(0xFFFFFFFF)

// 6. Cyber Amber (Warm Honey & Amber Accent)
val AmberPrimary = Color(0xFFD97706)
val AmberPrimaryContainer = Color(0xFFFEF3C7)
val AmberSecondary = Color(0xFFF59E0B)
val AmberTertiary = Color(0xFFB45309)
val AmberBackground = Color(0xFFFFFBEB)
val AmberSurface = Color(0xFFFFFFFF)

// 7. Sakura Pink (Soft Candy Rose & Lavender)
val SakuraPrimary = Color(0xFFDB2777)
val SakuraPrimaryContainer = Color(0xFFFCE7F3)
val SakuraSecondary = Color(0xFFF472B6)
val SakuraTertiary = Color(0xFFA855F7)
val SakuraBackground = Color(0xFFFDF2F8)
val SakuraSurface = Color(0xFFFFFFFF)

// 8. Deep Midnight (Cobalt, Cyan Glow, Obsidian)
val MidnightPrimary = Color(0xFF38BDF8)
val MidnightPrimaryContainer = Color(0xFF0369A1)
val MidnightSecondary = Color(0xFF818CF8)
val MidnightTertiary = Color(0xFF34D399)
val MidnightBackground = Color(0xFF0B0F19)
val MidnightSurface = Color(0xFF111827)
val MidnightSurfaceVariant = Color(0xFF1F2937)

// 9. Expressive Berry (Mulberry Wine, Hot Magenta, Champagne)
val BerryPrimary = Color(0xFF9D174D)
val BerryPrimaryContainer = Color(0xFFFBCFE8)
val BerrySecondary = Color(0xFFBE185D)
val BerryTertiary = Color(0xFFD97706)
val BerryBackground = Color(0xFFFFF1F2)
val BerrySurface = Color(0xFFFFFFFF)
